### ISSUE TITLE
Topaz Armor Set Has Durability.

### ISSUE THREAD

**Issue by kenijey** [RedBullSlurpie/SlurpiesDongles#5]
i can upload a picture of it if you want. using 1.11.2 and latest version of mod. i **enchanted** them in enchantment table, and i am also using durabilityshow mod. it shows the durability. and the durability is also can be seen on the inventory, the green durability bar on the armor set parts.

**Comment by RedBullSlurpie** [comment]
I will take a look at this. Please excuse the delay, my grandmother has recently passed away so it's been a bit rough. Will look at it ASAP, and yes please post a picture as well as fill out this info IF applicable.
Forge Version-
Link too all of the other mods installed- (Just pastebin all of the mods names, and versions of the mods you are using and post the link here)
When does the issue occur?- 
Thank you

**Comment by RedBullSlurpie** [comment]
Hello there. I took a look at the config files for my mod and it turns out that the Topaz Armor HAS a durability set to 42 by default. This is the issue you are having. I will fix this issue in the next update, but for it to work for you, you must delete the config folder for my mod. To do this please go to the Minecraft folder for the modpack you are playing, open the Config folder, then delete the folder named  "Slurpie's Dongles". Once that folder is deleted, please update the mod to the new version and it will fix it's self. Thank you for your bug report, people like you is what helps me fix the mod. :)

**Comment by kenijey** [comment]
doesn't matter :)

**Comment by RedBullSlurpie** [comment]
What doesn't matter? Confused?

**Comment by kenijey** [comment]
no, for your thank. it doesn't matter :) i everytime help mods developers..
